'use client';
import {useMemo,useState} from 'react';
const initial=[
{id:1,name:'Julien Martin',phone:'06 12 34 56 78',car:'Peugeot 308',plate:'AB-123-CD',problem:'Voyant moteur allumé',status:'Nouveau'},
{id:2,name:'Sarah Lopez',phone:'06 98 76 54 32',car:'Renault Clio V',plate:'EF-456-GH',problem:'Freins qui sifflent',status:'À rappeler'},
{id:3,name:'Marc Bernard',phone:'06 45 21 90 11',car:'BMW Série 1',plate:'JK-789-LM',problem:'Révision + vidange',status:'RDV confirmé'}];
const steps=['Nouveau','À rappeler','RDV confirmé','En atelier','Terminé'];
const nav=[['dashboard','Tableau de bord'],['demandes','Demandes'],['agenda','Rendez-vous'],['devis','Devis'],['assistant','Assistant IA'],['widget','Widget site'],['settings','Paramètres']];
export default function Home(){
 const [tab,setTab]=useState('dashboard'),[requests,setRequests]=useState(initial),[msg,setMsg]=useState(''),[chat,setChat]=useState([{who:'ai',text:'Bonjour 👋 Je suis NOVA. Quel problème rencontrez-vous avec votre véhicule ?'}]);
 const stats=useMemo(()=>({all:requests.length,new:requests.filter(x=>x.status==='Nouveau').length,rdv:requests.filter(x=>x.status==='RDV confirmé').length,done:requests.filter(x=>x.status==='Terminé').length}),[requests]);
 function advance(id){setRequests(r=>r.map(x=>x.id===id?{...x,status:steps[Math.min(steps.indexOf(x.status)+1,steps.length-1)]}:x))}
 function send(){if(!msg.trim())return;const text=msg.trim();const turn=chat.filter(x=>x.who==='me').length;let answer=['Merci. Quel est le modèle du véhicule et son immatriculation ?','D’accord. Pouvez-vous me donner votre nom et votre numéro de téléphone ?','Parfait. Quel créneau vous conviendrait pour être rappelé ou passer au garage ?','Votre demande est enregistrée. Le garage dispose maintenant du résumé et pourra vous recontacter.'][Math.min(turn,3)];setChat(c=>[...c,{who:'me',text},{who:'ai',text:answer}]);setMsg('')}
 return <main><aside><div className="brand"><b>NOVA</b><span>GARAGE</span></div>{nav.map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{v}</button>)}<div className="garage"><b>Garage Démo</b><small>NOVA Pro • En ligne</small></div></aside>
 <section><header><div><h1>{tab==='dashboard'?'Bonjour 👋':'NOVA Garage'}</h1><p>Votre centre de pilotage client, atelier et IA.</p></div><button className="primary" onClick={()=>setTab('assistant')}>+ Nouvelle demande</button></header>
 {tab==='dashboard'&&<><div className="cards"><Card n={stats.all} t="Demandes"/><Card n={stats.new} t="Nouvelles"/><Card n={stats.rdv} t="RDV confirmés"/><Card n={stats.done} t="Terminées"/></div><Requests rows={requests} advance={advance}/></>}
 {tab==='demandes'&&<Requests rows={requests} advance={advance}/>} 
 {tab==='agenda'&&<Panel title="Rendez-vous"><div className="appointment"><b>09:00</b><span>Julien Martin — Peugeot 308</span><em>Diagnostic</em></div><div className="appointment"><b>11:30</b><span>Sarah Lopez — Renault Clio V</span><em>Freinage</em></div><div className="appointment"><b>14:00</b><span>Marc Bernard — BMW Série 1</span><em>Révision</em></div></Panel>}
 {tab==='devis'&&<Panel title="Devis"><div className="quote"><b>DEV-001</b><span>Révision Peugeot 308</span><strong>289 €</strong></div><div className="quote"><b>DEV-002</b><span>Plaquettes Renault Clio</span><strong>240 €</strong></div><button className="primary">Créer un devis</button></Panel>}
 {tab==='assistant'&&<div className="split"><Panel title="NOVA Assistant"><div className="chat">{chat.map((m,i)=><div className={'bubble '+m.who} key={i}>{m.text}</div>)}</div><div className="composer"><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Écrivez votre message…"/><button className="primary" onClick={send}>Envoyer</button></div></Panel><Panel title="Qualification automatique"><p>NOVA collecte le problème, le véhicule, l’immatriculation, les coordonnées et le créneau souhaité.</p><div className="success">● Assistant disponible 24/7</div><p className="muted">La V1 commerciale branchera ensuite un véritable modèle IA côté serveur.</p></Panel></div>}
 {tab==='widget'&&<div className="split"><Panel title="Widget pour le site du garage"><p>Le garage colle un petit script sur son site. Le bouton NOVA apparaît alors sur toutes les pages.</p><pre>{`<script src="https://app.novagarage.fr/widget.js" data-garage="garage-martin"></script>`}</pre><p className="muted">Le domaine est un exemple tant que le produit n’est pas déployé.</p></Panel><Panel title="Aperçu client"><div className="sitepreview"><h3>Garage Martin</h3><p>Entretien • Diagnostic • Freinage</p><button className="floating" onClick={()=>setTab('assistant')}>💬 Besoin d’aide ?</button></div></Panel></div>}
 {tab==='settings'&&<Panel title="Paramètres du garage"><label>Nom du garage<input defaultValue="Garage Démo"/></label><label>Téléphone<input defaultValue="04 91 00 00 00"/></label><label>Horaires<input defaultValue="Lun–Ven · 8h–18h"/></label><label>Services<input defaultValue="Entretien, diagnostic, freinage, pneus"/></label><button className="primary">Enregistrer</button></Panel>}
 </section></main>}
function Card({n,t}){return <div className="card"><span>{t}</span><strong>{n}</strong><small>Mis à jour en direct</small></div>}
function Panel({title,children}){return <div className="panel"><h2>{title}</h2>{children}</div>}
function Requests({rows,advance}){return <div className="panel"><div className="panelhead"><h2>Demandes clients</h2><span>{rows.length} demandes</span></div><div>{rows.map(r=><div className="row" key={r.id}><div><b>{r.name}</b><small>{r.phone}</small></div><div><b>{r.car} • {r.plate}</b><small>{r.problem}</small></div><span className="pill">{r.status}</span><button onClick={()=>advance(r.id)}>Avancer →</button></div>)}</div></div>}
